const styles = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: 20,
    listStyle: 'none',
    padding: 0,
    margin: 0,
    alignItems: 'start',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 8,
    padding: 8,
    background: '#0f0f10',
    border: '1px solid #222',
    borderRadius: 8,
    textAlign: 'left',
    cursor: 'pointer',
    width: '100%',
    boxSizing: 'border-box',
    position: 'relative',
    zIndex: 0,
  },
  thumbWrapper: {
    width: '100%',
    aspectRatio: '16 / 9',
    overflow: 'hidden',
    borderRadius: 6,
    background: '#0b0b0b',
    flexShrink: 0,
  },
  thumb: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  title: {
    fontSize: 13,
    color: '#e6f9f9',
    margin: 0,
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};

export default styles;
