const styles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: 16,
    listStyle: "none",
    padding: 0,
    margin: 0,
    alignItems: "start",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
    padding: 12,
    background: "linear-gradient(180deg, #0f1220 0%, #0b0b12 100%)",
    border: "1px solid rgba(255,255,255,0.03)",
    borderRadius: 12,
    textAlign: "left",
    cursor: "pointer",
    width: "100%",
    boxSizing: "border-box",
    position: "relative",
    zIndex: 0,
    transition: "transform 0.18s ease, box-shadow 0.18s ease",
    boxShadow: "0 4px 12px rgba(2,6,23,0.6)",
  },
  cardHover: {
    transform: "translateY(-6px) scale(1.02)",
    boxShadow: "0 14px 36px rgba(2,6,23,0.72)",
  },
  cardFocus: {
    outline: "3px solid rgba(30,255,210,0.12)",
    boxShadow: "0 10px 30px rgba(2,6,23,0.72)",
  },
  thumbWrapper: {
    width: "100%",
    aspectRatio: "16 / 9",
    overflow: "hidden",
    borderRadius: 6,
    background: "#0b0b0b",
    flexShrink: 0,
  },
  thumb: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    objectPosition: "center",
    background: "#000",
    display: "block",
  },
  title: {
    fontSize: 13,
    color: "#e6f9f9",
    margin: 0,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
};

export default styles;
